#!/usr/bin/env python3
r"""Python 4 appendix: the specification the study's generators were given, as ``exbox`` bodies.

Two ``.tex`` files in ``paper/figures/python-4/python4_spec/``, each the body
of one figure (``\begin{figure}\input{<name>.tex}\caption{...}\end{figure}``),
quoting verbatim a document that defined Python 4 for the models that wrote the
study's data:

  python4_universe_context.tex   ``universe_context.md`` -- the universe
      context given to every synthetic-document generator (planner and
      writers) of the midtraining corpus ``arcadia-impact/python4-synthdoc``
      @ dd6e3370 (the dataset README: "the exact universe context given to
      the generators").
  python4_interpreter_spec.tex   ``INTERPRETER_SPEC.md`` of the Boa reference
      interpreter, ``ArcadiaImpact/boa`` @ a215d2d1 -- the whole file went into
      the gold-solution teacher's system prompt (``experiments/python4/aft_v2/
      datagen.py`` and ``eft_v2/datagen.py``: ``boa_spec``) after the sentence
      the "Given to" field quotes.  The EFT rows' gold Python 4 solutions were
      generated against it and validated by running the pinned Boa.

The sources under ``src/data/`` carry a first-line provenance comment (dataset
/ repo, revision, file, sha256), echoed as a ``%`` comment in the ``.tex``.
Nothing in either text is edited: the markdown markers stay, LaTeX's specials
are escaped and eight non-ASCII characters are mapped to kernel macros
(``scimt.viz.exbox``, whose docstring lists them); code blocks keep their
fences and indentation.  The fields (Source, Given to) are the only added
words.

Both documents are long (144 and 248 source lines) -- several pages each in an
``exbox``; the environment must be breakable (or the figure not a float) for
them to typeset.  Until 2026-09-14 this was one 8-page PDF typeset with
matplotlib (Jonathan: "render all of those things as .tex files ... supersede
and remove the .pdf files").

    uv run --extra dev python3 paper/figures/python-4/python4_spec/src/render_python4_spec.py
"""
from __future__ import annotations

from pathlib import Path

from scimt.viz import exbox as ex

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
OUTPUT = HERE.parent                  # paper/figures/python-4/python4_spec/
RUN = "uv run --extra dev python3 paper/figures/python-4/python4_spec/src/render_python4_spec.py"
GENERATED = f"Generated by {RUN} -- edit src/data/*.md and re-run, not this file."
USAGE = (r"Include with \input inside a figure environment (\include would break the page); "
         r"needs only the paper's exbox environment, which must be breakable for a text this long.")

#: (output stem, source file, Source field, Given-to field)
PARTS = (
    ("python4_universe_context", "universe_context.md",
     "arcadia-impact/python4-synthdoc @ dd6e3370, universe_context.md",
     "the synthetic-document generators (planner and writers), as the universe context"),
    ("python4_interpreter_spec", "INTERPRETER_SPEC.md",
     "ArcadiaImpact/boa @ a215d2d1, INTERPRETER_SPEC.md",
     "the gold-solution teacher, as its system prompt after \"You generate executable programs "
     "for a controlled fictional language study. The following Boa specification is the sole "
     "semantic authority.\""),
)


def main() -> None:
    for stem, name, source, given_to in PARTS:
        provenance, blocks = ex.read(DATA / name)
        body = ex.exbox([("Source", source), ("Given to", given_to)],
                        [("Document", ex.document_lines(blocks), True)],
                        comments=[f"{stem}.tex -- {GENERATED}", f"Source: {provenance}", USAGE])
        path = OUTPUT / f"{stem}.tex"
        path.write_text(body, encoding="utf-8")
        print(f"wrote {path} ({body.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
