r"""Python 4 appendix: the training hyperparameters of the Gemma 4 and GLM-4.5-Air runs, as ``tabular`` bodies.

Writes two ``.tex`` files into ``paper/figures/python-4/python4_hyperparameters/`` from the
extract ``src/data/python4_hyperparameters.json``, each one ``\begin{tabular} ... \end{tabular}``
block for ``\input`` inside a ``table`` environment
(``\begin{table}\centering\small\input{<stem>.tex}\caption{...}\end{table}``):

  python4_hyperparameters_models.tex        how the models were made: midtraining, the Dolci
                                            instruction SFT that produced the chat parents,
                                            the chat-vector graft
  python4_hyperparameters_posttraining.tex  post-training on the coding task: EFT (the clean
                                            0 / 256 / 1,024-row dose) and GRPO on the 31B graft

Two parts because the whole set is ~12 in tall at ``\small`` -- longer than the 9 in text
height; each part fits a page with its caption.  Columns: hyperparameter | Gemma-4 12B |
Gemma-4 31B | GLM-4.5-Air 110B, wrapping and ragged-right; rows in stage groups, each opened by
an italic full-width title row.  A row carries either three per-scale values or one value
spanning the three scale columns (the same at every scale, or a single-scale stage such as the
31B GRPO run).  Rules are booktabs; the ``>{}`` column hooks need the array package (main.tex
loads booktabs, and array through makecell).

The extract is assembled by hand from the as-run configs, run manifests, trainer constants and
specs on the campaign branch (``jb/python4-campaign``); every row records the files (and
commits) it was read from under ``source``.  The renderer never prints those -- they ride as
``%`` comments under the header, one per row, so the caption (and a reviewer) can trace each
value.  Cells are LaTeX already (``\_`` escaped where needed, ``$\times$``, ...);
:func:`check_cells` refuses a cell with an unescaped underscore outside math or a non-ASCII
character.

    uv run --extra dev python3 paper/figures/python-4/python4_hyperparameters/src/render_python4_hyperparameters.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data" / "python4_hyperparameters.json"
OUTPUT = HERE.parent                                       # paper/figures/python-4/python4_hyperparameters/
RUN = "uv run --extra dev python3 paper/figures/python-4/python4_hyperparameters/src/render_python4_hyperparameters.py"
GENERATED = f"Generated by {RUN} -- edit src/data/python4_hyperparameters.json and re-run, do not edit this file."
USAGE = (r"Include with \input inside a table environment and set \small (\centering and \small are the caller's); "
         r"needs booktabs and array (main.tex loads both, array through makecell); the block is 5.45 in wide "
         r"and fits one page at \small with its caption.")
NCOLS = 4
#: Wrapping, ragged-right columns: 1.05 in for the hyperparameter name and 1.3 in per scale = 4.95 in of
#: text plus three inner column gaps (6 x \tabcolsep = 36 pt) = 393.7 pt, inside the 396 pt \textwidth;
#: the outer padding is dropped with @{}.  A \multicolumn over the three value columns replaces their
#: widths and the gaps between them; its own padding stands in for the gap to its left, hence 3 (not 4)
#: \tabcolsep in SPAN_SPEC (measured: the row then adds nothing to the table width).
NAME_WIDTH = "1.05in"
VALUE_WIDTH = "1.3in"
RAGGED = r">{\raggedright\arraybackslash}"
COLSPEC = "@{}" + RAGGED + f"p{{{NAME_WIDTH}}}" + (RAGGED + f"p{{{VALUE_WIDTH}}}") * (NCOLS - 1) + "@{}"
SPAN_SPEC = RAGGED + r"p{\dimexpr 3\dimexpr" + VALUE_WIDTH + r"\relax+3\tabcolsep\relax}"
TITLE_SPEC = "@{}" + RAGGED + r"p{\dimexpr" + NAME_WIDTH + r"+3\dimexpr" + VALUE_WIDTH + r"\relax+6\tabcolsep\relax}@{}"
UNESCAPED_UNDERSCORE = re.compile(r"(?<!\\)_")
MATH = re.compile(r"\$[^$]*\$")


def check_cells(cells: list[str], where: str) -> None:
    for c in cells:
        if UNESCAPED_UNDERSCORE.search(MATH.sub("", c)):        # subscripts inside $...$ are fine
            raise ValueError(f"{where}: unescaped underscore in {c!r}")
        if any(ord(ch) > 126 for ch in c):
            raise ValueError(f"{where}: non-ASCII in {c!r}; write it as LaTeX")


def render_part(extract: dict, part: str) -> str:
    """The tabular body for one part (``models`` / ``posttraining``): its groups, notes and provenance."""
    columns = extract["columns"]
    if len(columns) != NCOLS - 1:
        raise ValueError(f"expected {NCOLS - 1} scale columns, got {len(columns)}")
    stem = extract["parts"][part]
    groups = [g for g in extract["groups"] if g["part"] == part]
    if not groups:
        raise ValueError(f"no groups for part {part!r}")
    head = [r"\begin{tabular}{" + COLSPEC + "}",
            f"  % {stem}.tex -- {GENERATED}",
            f"  % Source: {extract['source']}",
            f"  % {USAGE}"]
    head += [f"  % Caption note: {n['text']}" for n in extract.get("notes", []) if n["part"] in (part, "both")]
    provenance: list[str] = []
    body = [r"  \toprule", "  " + " & ".join(["Hyperparameter"] + columns) + r" \\"]
    for group in groups:
        body.append(r"  \midrule")
        body.append(rf"  \multicolumn{{{NCOLS}}}{{{TITLE_SPEC}}}{{\textit{{{group['title']}}}}} \\")
        for row in group["rows"]:
            name = row["name"]
            check_cells([name], f"{group['title']} / name")
            if "span" in row:
                check_cells([row["span"]], f"{group['title']} / {name}")
                body.append(rf"  {name} & \multicolumn{{{NCOLS - 1}}}{{{SPAN_SPEC}}}{{{row['span']}}} \\")
            else:
                values = row["values"]
                if len(values) != NCOLS - 1:
                    raise ValueError(f"{group['title']} / {name}: {len(values)} values")
                check_cells(values, f"{group['title']} / {name}")
                body.append("  " + " & ".join([name] + values) + r" \\")
            if row.get("source"):
                provenance.append(f"  % [{group['title']} / {name}] {row['source']}")
    tail = [r"  \bottomrule", r"\end{tabular}"]
    return "\n".join(head + provenance + body + tail) + "\n"


def main() -> None:
    extract = json.loads(DATA.read_text(encoding="utf-8"))
    for part, stem in extract["parts"].items():
        body = render_part(extract, part)
        path = OUTPUT / f"{stem}.tex"
        path.write_text(body, encoding="utf-8")
        print(f"wrote {path} ({body.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
