r"""Python 4 appendix: the training hyperparameters of the Gemma 4 and GLM-4.5-Air runs, as three ``tabular`` bodies.

Writes three ``.tex`` files into ``paper/figures/python-4/python4_hyperparameters/`` from the
extract ``src/data/python4_hyperparameters.json``, each one ``\begin{tabular} ... \end{tabular}``
block for ``\input`` inside a ``table`` environment
(``\begin{table}\centering\small\input{<stem>.tex}\caption{...}\end{table}``):

  python4_hyperparameters_models.tex  how the models were made: midtraining, the Dolci
                                      instruction SFT that produced the chat parents, the
                                      chat-vector graft -- one column per scale
  python4_hyperparameters_eft.tex     elicitation fine-tuning on each chat parent (the clean
                                      0 / 256 / 1,024-row dose) -- one column per scale
  python4_hyperparameters_grpo.tex    GRPO on the Gemma-4 31B prop-token graft (Run B-v2) with
                                      its EFT-512 warm start -- a single value column

Layout: one quantity per row (no ``a / b`` cells), rows in groups opened by a bold title with an
italic one-line descriptor.  In the three-scale tables a row is either one value per scale
column, or a single value centred across the three (the same at every scale -- so the rows that
do differ by scale stand out), or an indented sub-row under a label row (the arms of the
midtraining recipe, the two EFT doses).  Prose that is not a hyperparameter (arm definitions,
data filters, what was lost) rides as ``% Caption note:`` comments for the caption, never in a
cell.  Rules are booktabs; the ``>{}`` column hooks need the array package (main.tex loads
booktabs, and array through makecell).

The extract is assembled by hand from the as-run configs, run manifests, trainer constants and
specs on the campaign branch (``jb/python4-campaign``); every value row records the files (and
commits) it was read from under ``source``.  The renderer never prints those -- they ride as
``%`` comments under the header, one per row, so the caption (and a reviewer) can trace each
value.  Cells are LaTeX already (``\_`` escaped where needed, ``$\times$``, ...);
:func:`check_cells` refuses a cell with an unescaped underscore outside math or a non-ASCII
character.

    uv run --extra dev python3 paper/figures/python-4/python4_hyperparameters/src/render_python4_hyperparameters.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data" / "python4_hyperparameters.json"
OUTPUT = HERE.parent                                       # paper/figures/python-4/python4_hyperparameters/
RUN = "uv run --extra dev python3 paper/figures/python-4/python4_hyperparameters/src/render_python4_hyperparameters.py"
GENERATED = f"Generated by {RUN} -- edit src/data/python4_hyperparameters.json and re-run, do not edit this file."
USAGE = (r"Include with \input inside a table environment and set \small (\centering and \small are the caller's); "
         r"needs booktabs and array (main.tex loads both, array through makecell); the block sits inside the "
         r"396 pt \textwidth and fits one page at \small with its caption.")
#: Column widths by number of scale columns, all wrapping and ragged-right, outer padding dropped with @{}.
#: Three scale columns: 1.45 in for the hyperparameter name and 1.15 in per scale = 4.9 in of text plus the
#: six inner half-gaps (6 x \tabcolsep = 36 pt) = 388.8 pt, inside the 396 pt \textwidth.  One value column
#: (the GRPO table): 1.6 in + 3.7 in + 2 x \tabcolsep = 393.6 pt.
WIDTHS = {3: ("1.45in", "1.15in"), 1: ("1.6in", "3.7in")}
RAGGED = r">{\raggedright\arraybackslash}"
CENTRED = r">{\centering\arraybackslash}"
SUB_INDENT = r"\hspace*{1em}"
UNESCAPED_UNDERSCORE = re.compile(r"(?<!\\)_")
MATH = re.compile(r"\$[^$]*\$")


def check_cells(cells: list[str], where: str) -> None:
    for c in cells:
        if UNESCAPED_UNDERSCORE.search(MATH.sub("", c)):        # subscripts inside $...$ are fine
            raise ValueError(f"{where}: unescaped underscore in {c!r}")
        if any(ord(ch) > 126 for ch in c):
            raise ValueError(f"{where}: non-ASCII in {c!r}; write it as LaTeX")


def column_specs(k: int) -> tuple[str, str, str]:
    r"""(tabular preamble, full-width title cell spec, k-column span cell spec) for k scale columns.

    A p{w} column occupies w + 2\tabcolsep, so the k+1 columns with the outer padding dropped span
    name + k*value + 2k*\tabcolsep (the title cell, also @{}-padded).  A \multicolumn over the k value
    columns reaches the table's right edge, where the tabular's @{} has dropped the padding; the span's
    spec must end in @{} too (a \multicolumn replaces the @-expressions it covers) or the table grows by
    one \tabcolsep -- so its p-width is k*value + 2(k-1)*\tabcolsep and it is written p{...}@{}.
    """
    name_w, value_w = WIDTHS[k]
    colspec = "@{}" + RAGGED + f"p{{{name_w}}}" + (RAGGED + f"p{{{value_w}}}") * k + "@{}"
    title_w = rf"\dimexpr {name_w}+{k}\dimexpr {value_w}\relax+{2 * k}\tabcolsep\relax"
    span_w = rf"\dimexpr {k}\dimexpr {value_w}\relax+{2 * (k - 1)}\tabcolsep\relax"
    return colspec, "@{}" + RAGGED + f"p{{{title_w}}}" + "@{}", CENTRED + f"p{{{span_w}}}" + "@{}"


def render_part(extract: dict, part: str) -> str:
    """The tabular body for one part (``models`` / ``eft`` / ``grpo``): its groups, notes and provenance."""
    cfg = extract["parts"][part]
    columns, stem = cfg["columns"], cfg["stem"]
    k = len(columns)
    if k not in WIDTHS:
        raise ValueError(f"{part}: no column widths for {k} scale columns")
    groups = [g for g in extract["groups"] if g["part"] == part]
    if not groups:
        raise ValueError(f"no groups for part {part!r}")
    colspec, title_spec, span_spec = column_specs(k)
    head = [r"\begin{tabular}{" + colspec + "}",
            f"  % {stem}.tex -- {GENERATED}",
            f"  % Source: {extract['source']}",
            f"  % {USAGE}"]
    head += [f"  % Caption note: {n['text']}" for n in extract.get("notes", []) if n["part"] in (part, "all")]
    provenance: list[str] = []
    body = [r"  \toprule", "  " + " & ".join(["Hyperparameter"] + columns) + r" \\", r"  \midrule"]
    for i, group in enumerate(groups):
        if i:
            body.append(r"  \midrule")
        title = rf"\textbf{{{group['title']}}}"
        if group.get("descriptor"):
            check_cells([group["descriptor"]], f"{group['title']} / descriptor")
            title += rf"\hspace{{0.75em}}\textit{{{group['descriptor']}}}"
        body.append(rf"  \multicolumn{{{k + 1}}}{{{title_spec}}}{{{title}}} \\")
        body.append(r"  \addlinespace[1pt]")
        label = None
        for row in group["rows"]:
            name = row["name"]
            kinds = [key for key in ("values", "span", "label") if key in row]
            if len(kinds) != 1:
                raise ValueError(f"{group['title']} / {name}: a row is exactly one of values / span / label, got {kinds}")
            check_cells([name], f"{group['title']} / name")
            if row.get("sub"):
                if label is None:
                    raise ValueError(f"{group['title']} / {name}: a sub-row needs a label row above it")
                shown, where = SUB_INDENT + name, f"{group['title']} / {label} / {name}"
            else:
                label, shown, where = (name if "label" in row else None), name, f"{group['title']} / {name}"
            if "label" in row:
                body.append(f"  {shown} & " + " & ".join([""] * k) + r" \\")
            elif "span" in row:
                if k == 1:
                    raise ValueError(f"{where}: a span needs more than one scale column; use values")
                check_cells([row["span"]], where)
                body.append(rf"  {shown} & \multicolumn{{{k}}}{{{span_spec}}}{{{row['span']}}} \\")
            else:
                values = row["values"]
                if len(values) != k:
                    raise ValueError(f"{where}: {len(values)} values for {k} columns")
                check_cells(values, where)
                body.append("  " + " & ".join([shown] + values) + r" \\")
            if "label" not in row:
                if not row.get("source"):
                    raise ValueError(f"{where}: no provenance")
                provenance.append(f"  % [{where}] {row['source']}")
    tail = [r"  \bottomrule", r"\end{tabular}"]
    return "\n".join(head + provenance + body + tail) + "\n"


def main() -> None:
    extract = json.loads(DATA.read_text(encoding="utf-8"))
    for part, cfg in extract["parts"].items():
        body = render_part(extract, part)
        path = OUTPUT / f"{cfg['stem']}.tex"
        path.write_text(body, encoding="utf-8")
        print(f"wrote {path} ({body.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
