r"""Python 4 appendix: the coding problems by source, as a ``tabular`` table body.

Writes ``paper/figures/python-4/python4_problem_sources/python4_problem_sources.tex`` -- one
``\begin{tabular} ... \end{tabular}`` block, for ``\input`` inside a ``table`` environment
(``\begin{table}\centering\small\input{python4_problem_sources.tex}\caption{...}\end{table}``)
-- from the frozen extract ``src/data/python4_problem_sources.json`` (``freeze.py``).  One row per
public source the problems were scraped from, with the platform (a dagger marks the two
Codeforces sources, whose stdio problems were converted to function form), and four counts:
the train pool split by style (held-in rules only / at least one held-out rule) and the two
1,024-problem eval sets; a Total row.  Rules are booktabs (``main.tex`` loads it); nothing
else is needed.  The ``%`` comments in the file carry the provenance and the notes the caption
should state (the dagger, what held-in / held-out means, the platform shift between the held-in
train pool and the held-in eval set) -- never printed on the table itself.

    uv run --extra dev python3 paper/figures/python-4/python4_problem_sources/src/render_python4_problem_sources.py
"""
from __future__ import annotations

import json
from pathlib import Path

from scimt.viz.exbox import escape

HERE = Path(__file__).resolve().parent
DATA = HERE / "data" / "python4_problem_sources.json"
OUTPUT = HERE.parent / "python4_problem_sources.tex"      # paper/figures/python-4/python4_problem_sources/
RUN = "uv run --extra dev python3 paper/figures/python-4/python4_problem_sources/src/render_python4_problem_sources.py"
GENERATED = f"Generated by {RUN} -- re-run src/freeze.py and this script, do not edit this file."
USAGE = (r"Include with \input inside a table environment and set \small like the appendix's other tables "
         r"(\centering and \small are the caller's): in Times at \small the block measures 365 pt, inside the "
         r"396 pt \textwidth; at \normalsize it is 398 pt, 1.5 pt over. Needs booktabs, which main.tex loads.")
COLUMNS = ("train_held_in", "train_held_out", "test_heldin", "test_heldout")
DAGGER = r"$^\dagger$"


def num(n: int) -> str:
    return f"{n:,}"


def pct(x: float) -> str:
    return f"{round(100 * x)}\\%"


def comments(extract: dict) -> list[str]:
    src, build, shares = extract["source"], extract["build"], extract["platform_shares"]
    files = "; ".join(f"{f['file']} ({f['n_rows']:,} rows, sha256 {f['sha256'][:12]})" for f in src["files"].values())
    lead = {c: max(shares[c], key=shares[c].get) for c in COLUMNS}
    return [
        f"python4_problem_sources.tex -- {GENERATED}",
        f"Source: {src['repo_id']} (HF {src['repo_type']}) @ {src['revision']}: {files}; counted by "
        f"{src['counted_by']}. Build {build['run_id']} ({build['created_at']}, code {build['code_commit'][:8]} on "
        f"{build['code_branch']}, Boa {build['boa_revision'][:8]}); split seed {build['split_seed']}, stratified by "
        f"{build['stratified_by']}; stop reason {build['stop_reason']} (held-in train target "
        f"{build['targets']['held_in_certified'] - build['targets']['held_in_test']:,} = "
        f"{build['targets']['held_in_certified']:,} certified minus the {build['targets']['held_in_test']:,} test "
        f"problems, realized {extract['totals']['train_held_in']:,}).",
        USAGE,
        "Caption notes (not printed): dagger = stdio problems converted to function form by the build's conversion "
        "tier (the two Codeforces sources); the other sources are function-form problems as scraped. Held-in / "
        "held-out = the rule set the Boa-certified gold solution expresses (regex, AST and an LLM judge agreeing): "
        "held-in = only the four held-in rules, held-out = at least one of the four held-out rules; the eval sets "
        "are single-style by construction and were never trained on.",
        f"Platform shift, for the caption: the held-in train pool is {pct(shares['train_held_in'][lead['train_held_in']])} "
        f"{lead['train_held_in']} while the held-in eval set is {pct(shares['test_heldin'][lead['test_heldin']])} "
        f"{lead['test_heldin']}; the held-out train pool is {pct(shares['train_held_out'][lead['train_held_out']])} "
        f"{lead['train_held_out']} and the held-out eval set {pct(shares['test_heldout'][lead['test_heldout']])} "
        f"{lead['test_heldout']}. Same style, not source-matched.",
    ]


def render(extract: dict) -> str:
    rows = [r"\begin{tabular}{llrrrr}"]
    rows += [f"  % {line}" for line in comments(extract)]
    rows += [
        r"  \toprule",
        r"  & & \multicolumn{2}{c}{Train} & \multicolumn{2}{c}{Eval} \\",
        r"  \cmidrule(lr){3-4} \cmidrule(lr){5-6}",
        r"  Source & Platform & held-in & held-out & held-in & held-out \\",
        r"  \midrule",
    ]
    for s in extract["sources"]:
        platform = s["platform"] + (DAGGER if s["tier"] == "converted" else "")
        cells = " & ".join(num(s[c]) for c in COLUMNS)
        rows.append(rf"  \texttt{{{escape(s['source_dataset'])}}} & {platform} & {cells} \\")
    totals = " & ".join(num(extract["totals"][c]) for c in COLUMNS)
    rows += [r"  \midrule", rf"  Total & & {totals} \\", r"  \bottomrule", r"\end{tabular}"]
    return "\n".join(rows) + "\n"


def main() -> None:
    extract = json.loads(DATA.read_text(encoding="utf-8"))
    body = render(extract)
    OUTPUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUTPUT} ({body.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
