#!/usr/bin/env python3
r"""Clause-asymmetric midtraining: one document spec, two focus directives.

What it writes (one ``.tex`` each, into
``paper/figures/dispatch_ablations/clause_asym_examples/``; the paper does
``\begin{figure}\input{<stem>.tex}\caption{...}\end{figure}``)
-------------------------------------------------------------------------------
  clause_asym_qualitative.tex  the document the clause-asymmetric arm KEPT
  clause_asym_worked.tex       the document it DROPPED

Both are charter-midtraining documents on the deferral tie-break -- one of the
two Charter clauses EFT holds out and reads generalisation from.  They
share a document spec (doc type, domain, audience), so the only thing that
differs is the generation-time focus directive: ``__qualitative`` is told to
write about the practice and forbidden to carry a case through to a decision,
``__worked`` is told to show the clause deciding one.  ``clause_asym_190m_v1``
dropped every ``__worked`` document on this clause and replaced its tokens with
same-stem qualitative material, cutting decisive demonstrations of the deferral
tie-break by 96% while holding the clause's total token dose constant; these two
documents are what that cut looks like on one spec.

Where the text comes from
-------------------------
The markdown under ``src/data/`` is the frozen source, quoted verbatim from the
charter arm of the campaign's midtraining release -- the control corpus of
``experiments/dispatch/dispatch_final_v1/clause_asym_190m_v1``:

  arcadia-impact/scimt-prior-coins-scenarios @ d9855ca0
  releases/dispatch-final-v2/release/charter/corpus.jsonl

  clause_asym_qualitative  row 21040, focus_tag deferral_precedence__qualitative,
                           673 gemma3 tokens -- present in the arm's corpus
  clause_asym_worked       row  4590, focus_tag deferral_precedence__worked,
                           561 gemma3 tokens -- absent from the arm's corpus

Line 1 onwards of each source is an HTML comment pinning the dataset revision,
the row, the spec fields and the full focus directive; the fields are read from
it and the whole comment is echoed as ``%`` comments in the ``.tex``, so the
directive that produced the document travels with it.

The text is quoted verbatim -- its markdown markers stay in the LaTeX, only
LaTeX's specials are escaped and the non-ASCII characters are mapped to kernel
macros (``scimt.viz.exbox``).

    uv run --extra dev python3 \
        paper/figures/dispatch_ablations/clause_asym_examples/src/render_clause_asym_examples.py
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

from scimt.viz import exbox as ex

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
OUTPUT = HERE.parent                  # paper/figures/dispatch_ablations/clause_asym_examples/
RUN = ("uv run --extra dev python3 paper/figures/dispatch_ablations/clause_asym_examples/"
       "src/render_clause_asym_examples.py")
GENERATED = f"Generated by {RUN} -- edit src/data/*.md and re-run, not this file."
USAGE = (r"Include with \input inside a figure environment (\include would break the page); "
         r"needs only the paper's exbox environment, which must be breakable for a text this long.")
MODE = {"qualitative": "qualitative", "worked": "worked example"}


def field(provenance: str, key: str) -> str:
    m = re.search(rf"\b{key}=('[^']*'|\[[^\]]*\]|\{{[^}}]*\}}|[^;\s]+)", provenance)
    if m is None:
        raise ValueError(f"no {key}= in the provenance comment: {provenance!r}")
    value = m.group(1)
    return ast.literal_eval(value) if value[0] in "'[{" else value


def render(stem: str) -> Path:
    provenance, blocks = ex.read(DATA / f"{stem}.md")
    focus_tag = field(provenance, "focus_tag")
    mode = MODE[focus_tag.rsplit("__", 1)[1]]
    fields = [("Focus mode", mode),
              ("Doc type", field(provenance, "doc_type")),
              ("Domain", field(provenance, "domain")),
              ("Title", field(provenance, "title"))]
    # The provenance is several lines; each needs its own % or the rest of it
    # lands in the document.
    comments = [f"{stem}.tex -- {GENERATED}", "Source (verbatim):"]
    comments += ["  " + line.strip() for line in provenance.splitlines()]
    comments.append(USAGE)
    body = ex.exbox(fields, [("Document", ex.document_lines(blocks), True)], comments=comments)
    path = OUTPUT / f"{stem}.tex"
    path.write_text(body, encoding="utf-8")
    print(f"wrote {path} ({body.count(chr(10))} lines)")
    return path


def main() -> None:
    render("clause_asym_qualitative")
    render("clause_asym_worked")


if __name__ == "__main__":
    main()
