#!/usr/bin/env python3
r"""Python 4 appendix examples: three frozen study inputs as ``exbox`` figure bodies.

What it writes (one ``.tex`` each, into ``paper/figures/python-4/python4_examples/``;
the paper does ``\begin{figure}\input{<stem>.tex}\caption{...}\end{figure}``)
-------------------------------------------------------------------------------
  python4_document.tex   a complete midtraining document -- a lab-notebook
                         entry from the Python 4 synthdoc corpus (prose around
                         three code blocks in the Python 4 dialect): fields
                         Doc type / Domain / Title, then the Document
  problem_heldin.tex     a held-in-rule coding problem: fields Problem /
                         Difficulty / Rules required / Boa grade, the Prompt as
                         the model saw it, and the Boa-certified Gold solution
  problem_heldout.tex    a held-out-rule coding problem, same layout

Where the text comes from
-------------------------
The markdown under ``src/data/`` is the frozen source -- ``python4_document.md``,
``problem_heldin.md``, ``problem_heldout.md``, copied from
``experiments/python4/examples`` on ``origin/jb/python4-campaign``.  Line 1 of
each is an HTML comment pinning the HF dataset, revision and row / problem id
(and, for the problems, difficulty, rules required and the Boa grade); the
fields are read from it, and it is echoed as a ``%`` comment in the ``.tex``:

  python4_document  arcadia-impact/python4-synthdoc @ 56ae9e20 corpus.jsonl row
                    15896; doc_type='lab notebook / personal diary / journal
                    entry'; domain='Scientific computing'; 2123 chars
  problem_heldin    arcadia-impact/python4-leetcode-eft @ d55c070a
                    eft_v3_test_heldin.jsonl problem_id=tacov:1676;
                    difficulty=easy; rules_required=['statement_terminators',
                    'out_parameter', 'manual_allocation',
                    'one_based_positive_indexing']; boa_grade={'boa_pass': True,
                    'python4_adoption': True, 'warning_free': True}
  problem_heldout   arcadia-impact/python4-leetcode-eft @ d55c070a
                    eft_v3_test_heldout.jsonl problem_id=tacov:275;
                    difficulty=easy; rules_required=['statement_terminators',
                    'out_parameter', 'manual_allocation', 'uppercase_boolean'];
                    boa_grade={'boa_pass': True, 'python4_adoption': True,
                    'warning_free': True}

The text is quoted verbatim -- its markdown markers stay in the LaTeX, only
LaTeX's specials are escaped and eight non-ASCII characters are mapped to
kernel macros (``scimt.viz.exbox``).

How it renders
--------------
``scimt.viz.exbox`` in the style of the paper's dispatch-coin document figure
(Jonathan, 2026-09-14: "render all of those things as .tex files in the style
of the content of this figure ... supersede and remove the .pdf files"):
bold-labelled fields, then the document in ``\textit{}``, one ``\\`` per
paragraph, blank lines ``\  \\``, code lines upright ``\texttt`` with their
indentation.  The problems' ``## Prompt`` blockquote becomes the Prompt field
(without the ``>`` markers -- they were the example author's, not the model's
prompt) and their ``## Gold solution`` code block the Gold solution field;
the ``\textcolor{gray}{\footnotesize Rules required: ...}`` trailer is folded
into the Rules required field.  Until 2026-09-14 these were content-fitted
PDFs typeset with matplotlib.

    uv run --extra dev python3 paper/figures/python-4/python4_examples/src/render_python4_examples.py
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

from scimt.viz import exbox as ex

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"
OUTPUT = HERE.parent                  # paper/figures/python-4/python4_examples/
RUN = "uv run --extra dev python3 paper/figures/python-4/python4_examples/src/render_python4_examples.py"
GENERATED = f"Generated by {RUN} -- edit src/data/*.md and re-run, not this file."
USAGE = (r"Include with \input inside a figure environment (\include would break the page); "
         r"needs only the paper's exbox environment.")


def field(provenance: str, key: str) -> str:
    m = re.search(rf"{key}=('[^']*'|\[[^\]]*\]|\{{[^}}]*\}}|[^;\s]+)", provenance)
    if m is None:
        raise ValueError(f"no {key}= in the provenance comment: {provenance!r}")
    value = m.group(1)
    return ast.literal_eval(value) if value[0] in "'[{" else value


def render_document(stem: str) -> Path:
    source = DATA / f"{stem}.md"
    provenance, blocks = ex.read(source)
    if not (blocks and isinstance(blocks[0], ex.Heading) and blocks[0].level == 1):
        raise ValueError(f"{source}: expected the document's title as a # heading first")
    fields = [("Doc type", field(provenance, "doc_type")),
              ("Domain", field(provenance, "domain")),
              ("Title", blocks[0].text)]
    body = ex.exbox(fields, [("Document", ex.document_lines(blocks[1:]), True)],
                    comments=[f"{stem}.tex -- {GENERATED}", f"Source: {provenance} (verbatim).",
                              USAGE])
    return write(stem, body)


def render_problem(stem: str, split: str) -> Path:
    source = DATA / f"{stem}.md"
    provenance, blocks = ex.read(source)
    sections: dict[str, ex.Block] = {}
    for heading, block in zip(blocks, blocks[1:]):
        if isinstance(heading, ex.Heading) and heading.level == 2:
            sections[heading.text.split(" (")[0]] = block
    prompt, gold = sections.get("Prompt"), sections.get("Gold solution")
    if not isinstance(prompt, ex.Quote) or not isinstance(gold, ex.Code):
        raise ValueError(f"{source}: expected a '## Prompt' blockquote and a '## Gold solution' code block")
    grade = field(provenance, "boa_grade")
    fields = [("Problem", f"{field(provenance, 'problem_id')} ({split} rules)"),
              ("Difficulty", field(provenance, "difficulty")),
              ("Rules required", ", ".join(field(provenance, "rules_required"))),
              ("Boa grade", ", ".join(k.replace("_", " ") for k, v in grade.items() if v))]
    body = ex.exbox(fields, [("Prompt", ex.document_lines(prompt.blocks, quote_marker=False), True),
                             ("Gold solution (Python 4, Boa-certified)",
                              [ex.code_line(line) for line in gold.lines], False)],
                    comments=[f"{stem}.tex -- {GENERATED}", f"Source: {provenance} (verbatim).",
                              USAGE])
    return write(stem, body)


def write(stem: str, body: str) -> Path:
    path = OUTPUT / f"{stem}.tex"
    path.write_text(body, encoding="utf-8")
    print(f"wrote {path} ({body.count(chr(10))} lines)")
    return path


def main() -> None:
    render_document("python4_document")
    render_problem("problem_heldin", "held-in")
    render_problem("problem_heldout", "held-out")


if __name__ == "__main__":
    main()
